image: python:3.6

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.

before_script:
  - pip install -U pytest

test:
  script:
    - mkdir build
    - py.test --junitxml build/results.xml src/test/test.py

  artifacts:
    when: always
    paths:
      - build/*.xml


